import type { Metadata } from "next";
import "./globals.css";
import { cookies, headers } from "next/headers";
import { Locale, resolveLocale } from "@repo/i18n";
import { getMessages } from "@repo/i18n/server";
import { Providers } from "./providers";
import { yekanBakh } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const headerStore = await headers();
  const locale: Locale = resolveLocale({
    locale:
      cookieStore.get("NEXT_LOCALE")?.value ?? cookieStore.get("locale")?.value,
    acceptLanguage: headerStore.get("accept-language"),
  });
  const messages = await getMessages(locale);

  return (
    <html
      lang={locale}
      dir="rtl"
      suppressHydrationWarning
      className={yekanBakh.variable}
    >
      <body className="font-sans">
        <Providers locale={locale} messages={messages}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
