import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "@repo/i18n/client";
import { getLocale, getMessages } from "@repo/i18n/server";
import { ThemeProvider } from "@repo/theme";
import { ApiProvider } from "@repo/api";
// import "@repo/theme/theme";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages(locale);
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ApiProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ApiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
